---
collections:
  - name: infra.aap_configuration
  - name: infra.aap_configuration_extended
  - name: ansible.controller
  - name: ansible.platform
  - name: ansible.utils
  - name: ansible.hub
  - name: ansible.eda
